### ISSUE TITLE
Pain WG analysis

### ISSUE THREAD

**Issue by Hamedhm** [mpi2/impc_stats_pipeline#2]
# Project name
Pain WG data analysis

# Project purpose
Pain WG

# Members involved in this project
  [x] @Hamedhm 

# Project estimated time (day/week/month)
2 days

# Project completed steps
 [] Analysing the data

# Project requirement
- All met

**Comment by jmason-ebi** [comment]
Is this done?

**Comment by Hamedhm** [comment]
@jmason-ebi  Not yet!
