### ISSUE TITLE
DR11 statistical analysis

### ISSUE THREAD

**Issue by Hamedhm** [mpi2/impc_stats_pipeline#3]
# IMPC statistical analysis for the DR11/windowing

# Project purpose
- Various papers/WGs/Groups that use windowing results

# Members involved in this project
  - [x] @Hamedhm 

# Project estimated time 
 - [x] 1 week

# Project completed steps
 - [x] Data preparation
 - [ ] Running the pipeline
 - [ ] Aggregating the results
 - [ ] Preparing the spreadsheets

# Project requirement
- [x] Parquet files

**Comment by jmason-ebi** [comment]
Is this done?
