### ISSUE TITLE
The plot for the German WG

### ISSUE THREAD

**Issue by Hamedhm** [mpi2/impc_stats_pipeline#5]
# Project name
The dispersion plot for the German WG

# Project purpose
- Paper

# Members involved in this project
  - [x] @Hamedhm 

# Project estimated time (day/week/month)
- Not clear

# Project requirement
- knowledge transfer

**Comment by viomunoz** [comment]
Pleiotropy figure for cardio genes requested.

**Comment by jmason-ebi** [comment]
Violeta to confirm with the user which data release.

**Comment by viomunoz** [comment]
Should be based on DR 10.1 (pleiotropy figure for the cardio paper)

**Comment by viomunoz** [comment]
Discussed internally: we need MP ids for the windowed results fro DR10.1

**Comment by jmason-ebi** [comment]
@Hamedhm When we last spoke about this ticket, we determined that we had the MP terms for DR10.0.  We need to generate the same report for DR 10.1.  If I recall, this was done by

1) @Hamedhm produces a database with the results from the stats pipeline in correct tables
2) @jmason-ebi reads that database and populates a pre-loaded DR10.1 
3) @jmason-ebi Restarts the data release process from the Ontology Annotation step, which will eventually push the results to DEV site
4) (optional, but recommended) To archive this into the FTP site as DR10.1-windowed, and include all solr cores, database, reports, and docker container to support the cardio paper

**Comment by jmason-ebi** [comment]
Need meeting with @Hamedhm and @jmason-ebi
