### ISSUE TITLE
[Embryo] Gross morphology data shouldn't be analysed by the stats pipeline

### ISSUE THREAD

**Issue by ficolo** [mpi2/impc_stats_pipeline#58]
The Gross Morphology data gets annotated on the ETL using the following rule:

If zyg in [hom, hem] and 'abnormal' count >= 2 then is a significant result
If zyg = het and 'abnormal' count >= 4 then is a significant result

All other cases are not significant results.

Noticed the stats pipeline is producing P-values for these parameters and it should process them at all, see:

https://www.mousephenotype.org/data/charts?accession=MGI:88180&allele_accession_id=MGI:5699604&zygosity=homozygote&parameter_stable_id=IMPC_GEL_032_001&pipeline_stable_id=BCM_001&procedure_stable_id=IMPC_GEL_003&parameter_stable_id=IMPC_GEL_032_001&phenotyping_center=BCM

https://www.mousephenotype.org/data/charts?accession=MGI:88180&allele_accession_id=MGI:5699604&pipeline_stable_id=BCM_001&procedure_stable_id=IMPC_GEL_003&parameter_stable_id=IMPC_GEL_014_001&zygosity=homozygote&phenotyping_center=BCM

It looks like the p-value is not significant but we marked as significant following the rule above.

**Comment by marinak-ebi** [comment]
I've executed statistical pipeline on the test data twice: without changes in `Late adults stats pipeline/DRrequiredAgeing/DRrequiredAgeingPackage/inst/extdata/ExceptionMap.list` and after adding "IMPC_GEL_006_001", "IMPC_GEL_011_001", "IMPC_GEL_014_001", "IMPC_GEL_015_001", "IMPC_GEL_019_001", "IMPC_GEL_032_001", "IMPC_GEL_011_001" mentioned above.

All files renamed from `output_Successful.tsv` → `output_NotProcessed.tsv`, which means that this fix worked. 
I'm going to add [all 42 parameters](https://www.mousephenotype.org/impress/ProcedureInfo?action=list&procID=874&pipeID=13) to the `ExceptionMap.list`

**Comment by ficolo** [comment]
"IMPC_EVL_001_001",908,
        "IMPC_EVM_001_001",966,
        "IMPC_EVO_001_001",528,
        "IMPC_EVP_001_001",545,
        "IMPC_GEL_006_001",575,
        "IMPC_GEL_011_001",1036,
        "IMPC_GEL_014_001",582,
        "IMPC_GEL_015_001",928,
        "IMPC_GEL_017_002",1030,
        "IMPC_GEL_018_001",943,
        "IMPC_GEL_019_001",1225,
        "IMPC_GEL_024_001",995,
        "IMPC_GEL_027_001",1225,
        "IMPC_GEL_028_001",1225,
        "IMPC_GEL_029_001",1225,
        "IMPC_GEL_030_001",777,
        "IMPC_GEL_032_001",1106,
        "IMPC_GEL_033_001",1036,
        "IMPC_GEL_036_002",1106,
        "IMPC_GEL_037_002",1181,
        "IMPC_GEL_038_001",1036,
        "IMPC_GEL_042_001",1031,
        "IMPC_GEL_055_001",456,
        "IMPC_GEL_056_001",724,
        "IMPC_GEL_057_001",1034,
        "IMPC_GEL_058_001",1034,
        "IMPC_GEL_059_001",990,
        "IMPC_GEL_060_001",984,
        "IMPC_GEL_061_001",1029,
        "IMPC_GEL_063_001",1146,
        "IMPC_GEL_064_001",1031,
        "IMPC_GEL_065_001",803,
        "IMPC_GEL_066_001",490,
        "IMPC_GEM_007_001",1019,
        "IMPC_GEM_016_002",1044,
        "IMPC_GEM_017_001",701,
        "IMPC_GEM_019_001",1044,
        "IMPC_GEM_021_001",704,
        "IMPC_GEM_024_001",433,
        "IMPC_GEM_025_002",1044,
        "IMPC_GEM_026_002",1044,
        "IMPC_GEM_027_001",1044,
        "IMPC_GEM_028_001",433,
        "IMPC_GEM_029_001",730,
        "IMPC_GEM_032_001",718,
        "IMPC_GEM_033_002",1043,
        "IMPC_GEM_036_001",1042,
        "IMPC_GEM_041_001",677,
        "IMPC_GEM_043_002",733,
        "IMPC_GEM_044_002",733,
        "IMPC_GEM_047_001",724,
        "IMPC_GEM_060_001",359,
        "IMPC_GEM_061_001",655,
        "IMPC_GEM_062_001",944,
        "IMPC_GEM_063_001",727,
        "IMPC_GEM_064_001",433,
        "IMPC_GEM_065_001",705,
        "IMPC_GEM_066_001",415,
        "IMPC_GEM_067_001",409,
        "IMPC_GEM_068_001",1041,
        "IMPC_GEM_069_001",1043,
        "IMPC_GEM_070_001",1041,
        "IMPC_GEM_071_001",728,
        "IMPC_GEM_072_001",412,
        "IMPC_GEM_073_001",406,
        "IMPC_GEM_075_001",730,
        "IMPC_GEM_076_001",726,
        "IMPC_GEM_077_001",726,
        "IMPC_GEM_078_001",335,
        "IMPC_GEM_079_001",2,
        "IMPC_GEO_001_001",1,
        "IMPC_GEO_002_001",1,
        "IMPC_GEO_003_001",1,
        "IMPC_GEO_004_001",1,
        "IMPC_GEO_005_001",1,
        "IMPC_GEO_006_001",1,
        "IMPC_GEO_008_001",273,
        "IMPC_GEO_009_002",681,
        "IMPC_GEO_011_001",306,
        "IMPC_GEO_013_001",1,
        "IMPC_GEO_014_001",1,
        "IMPC_GEO_015_001",489,
        "IMPC_GEO_016_001",334,
        "IMPC_GEO_017_002",382,
        "IMPC_GEO_018_002",490,
        "IMPC_GEO_019_001",573,
        "IMPC_GEO_022_001",300,
        "IMPC_GEO_023_001",1,
        "IMPC_GEO_026_002",1,
        "IMPC_GEO_027_001",1,
        "IMPC_GEO_028_001",204,
        "IMPC_GEO_029_001",386,
        "IMPC_GEO_030_001",579,
        "IMPC_GEO_031_001",1,
        "IMPC_GEO_032_001",1,
        "IMPC_GEO_033_001",684,
        "IMPC_GEO_034_002",684,
        "IMPC_GEO_035_001",1,
        "IMPC_GEO_036_001",1,
        "IMPC_GEO_037_001",508,
        "IMPC_GEO_038_002",391,
        "IMPC_GEO_039_001",1,
        "IMPC_GEO_040_001",1,
        "IMPC_GEO_041_002",489,
        "IMPC_GEO_042_002",441,
        "IMPC_GEO_043_002",488,
        "IMPC_GEO_044_001",1,
        "IMPC_GEO_045_001",1,
        "IMPC_GEO_046_001",1,
        "IMPC_GEO_047_002",587,
        "IMPC_GEO_048_002",590,
        "IMPC_GEO_061_001",201,
        "IMPC_GEO_062_001",487,
        "IMPC_GEO_063_001",680,
        "IMPC_GEO_064_001",680,
        "IMPC_GEO_065_001",680,
        "IMPC_GEO_066_001",485,
        "IMPC_GEO_067_001",485,
        "IMPC_GEO_069_001",486,
        "IMPC_GEO_070_001",522,
        "IMPC_GEO_071_001",377,
        "IMPC_GEO_072_001",515,
        "IMPC_GEP_004_002",484,
        "IMPC_GEP_005_002",715,
        "IMPC_GEP_010_001",435,
        "IMPC_GEP_011_002",855,
        "IMPC_GEP_013_001",528,
        "IMPC_GEP_015_001",858,
        "IMPC_GEP_016_001",822,
        "IMPC_GEP_017_001",852,
        "IMPC_GEP_018_002",854,
        "IMPC_GEP_022_001",815,
        "IMPC_GEP_024_001",857,
        "IMPC_GEP_026_001",858,
        "IMPC_GEP_029_002",715,
        "IMPC_GEP_030_002",857,
        "IMPC_GEP_033_001",530,
        "IMPC_GEP_034_001",850,
        "IMPC_GEP_035_001",760,
        "IMPC_GEP_036_001",541,
        "IMPC_GEP_038_001",850,
        "IMPC_GEP_039_002",858,
        "IMPC_GEP_042_001",528,
        "IMPC_GEP_047_002",858,
        "IMPC_GEP_048_002",858,
        "IMPC_GEP_049_002",856,
        "IMPC_GEP_052_001",708,
        "IMPC_GEP_059_002",760,
        "IMPC_GEP_060_002",858,
        "IMPC_GEP_061_002",802,
        "IMPC_GEP_075_001",541,
        "IMPC_GEP_076_001",856,
        "IMPC_GEP_078_001",484,
        "IMPC_GEP_079_001",581,
        "IMPC_GEP_080_001",579,
        "IMPC_GEP_081_001",530,
        "IMPC_GEP_082_001",858,
        "IMPC_GEP_083_001",483,
        "IMPC_GEP_084_001",854,
        "IMPC_GEP_086_001",757,
        "IMPC_GEP_087_001",818,
        "IMPC_GPL_001_001",747,
        "IMPC_GPL_002_001",747,
        "IMPC_GPL_003_001",747,
        "IMPC_GPL_004_001",747,
        "IMPC_GPL_005_001",552,
        "IMPC_GPM_001_001",569,
        "IMPC_GPM_002_001",636,
        "IMPC_GPM_003_001",636,
        "IMPC_GPM_004_001",956,
        "IMPC_GPM_005_001",636,
        "IMPC_GPM_018_001",289,
        "IMPC_GPO_001_001",418,
        "IMPC_GPO_002_001",604,
        "IMPC_GPO_003_001",604,
        "IMPC_GPO_004_001",569,
        "IMPC_GPO_005_001",409,
        "IMPC_GPO_018_001",90,
        "IMPC_GPP_001_001",671,
        "IMPC_GPP_002_001",708,
        "IMPC_GPP_003_001",717,
        "IMPC_GPP_004_001",768,
        "IMPC_GPP_005_001",714,
        "IMPC_GPP_018_001",404

**Comment by marinak-ebi** [comment]
I added those parameters in a file here: `Late adults stats pipeline/DRrequiredAgeing/DRrequiredAgeingPackage/inst/extdata/ExceptionMap.list`
> ```
> IMPC_EVL_001_001
> IMPC_EVM_001_001
> IMPC_EVO_001_001
> IMPC_EVP_001_001
> IMPC_GEL_006_001
> IMPC_GEL_011_001
> IMPC_GEL_014_001
> IMPC_GEL_015_001
> IMPC_GEL_017_002
> IMPC_GEL_018_001
> IMPC_GEL_019_001
> IMPC_GEL_024_001
> IMPC_GEL_027_001
> IMPC_GEL_028_001
> IMPC_GEL_029_001
> IMPC_GEL_030_001
> IMPC_GEL_032_001
> IMPC_GEL_033_001
> IMPC_GEL_036_002
> IMPC_GEL_037_002
> IMPC_GEL_038_001
> IMPC_GEL_042_001
> IMPC_GEL_055_001
> IMPC_GEL_056_001
> IMPC_GEL_057_001
> IMPC_GEL_058_001
> IMPC_GEL_059_001
> IMPC_GEL_060_001
> IMPC_GEL_061_001
> IMPC_GEL_063_001
> IMPC_GEL_064_001
> IMPC_GEL_065_001
> IMPC_GEL_066_001
> IMPC_GEM_007_001
> IMPC_GEM_016_002
> IMPC_GEM_017_001
> IMPC_GEM_019_001
> IMPC_GEM_021_001
> IMPC_GEM_024_001
> IMPC_GEM_025_002
> IMPC_GEM_026_002
> IMPC_GEM_027_001
> IMPC_GEM_028_001
> IMPC_GEM_029_001
> IMPC_GEM_032_001
> IMPC_GEM_033_002
> IMPC_GEM_036_001
> IMPC_GEM_041_001
> IMPC_GEM_043_002
> IMPC_GEM_044_002
> IMPC_GEM_047_001
> IMPC_GEM_060_001
> IMPC_GEM_061_001
> IMPC_GEM_062_001
> IMPC_GEM_063_001
> IMPC_GEM_064_001
> IMPC_GEM_065_001
> IMPC_GEM_066_001
> IMPC_GEM_067_001
> IMPC_GEM_068_001
> IMPC_GEM_069_001
> IMPC_GEM_070_001
> IMPC_GEM_071_001
> IMPC_GEM_072_001
> IMPC_GEM_073_001
> IMPC_GEM_075_001
> IMPC_GEM_076_001
> IMPC_GEM_077_001
> IMPC_GEM_078_001
> IMPC_GEM_079_001
> IMPC_GEO_001_001
> IMPC_GEO_002_001
> IMPC_GEO_003_001
> IMPC_GEO_004_001
> IMPC_GEO_005_001
> IMPC_GEO_006_001
> IMPC_GEO_008_001
> IMPC_GEO_009_002
> IMPC_GEO_011_001
> IMPC_GEO_013_001
> IMPC_GEO_014_001
> IMPC_GEO_015_001
> IMPC_GEO_016_001
> IMPC_GEO_017_002
> IMPC_GEO_018_002
> IMPC_GEO_019_001
> IMPC_GEO_022_001
> IMPC_GEO_023_001
> IMPC_GEO_026_002
> IMPC_GEO_027_001
> IMPC_GEO_028_001
> IMPC_GEO_029_001
> IMPC_GEO_030_001
> IMPC_GEO_031_001
> IMPC_GEO_032_001
> IMPC_GEO_033_001
> IMPC_GEO_034_002
> IMPC_GEO_035_001
> IMPC_GEO_036_001
> IMPC_GEO_037_001
> IMPC_GEO_038_002
> IMPC_GEO_039_001
> IMPC_GEO_040_001
> IMPC_GEO_041_002
> IMPC_GEO_042_002
> IMPC_GEO_043_002
> IMPC_GEO_044_001
> IMPC_GEO_045_001
> IMPC_GEO_046_001
> IMPC_GEO_047_002
> IMPC_GEO_048_002
> IMPC_GEO_061_001
> IMPC_GEO_062_001
> IMPC_GEO_063_001
> IMPC_GEO_064_001
> IMPC_GEO_065_001
> IMPC_GEO_066_001
> IMPC_GEO_067_001
> IMPC_GEO_069_001
> IMPC_GEO_070_001
> IMPC_GEO_071_001
> IMPC_GEO_072_001
> IMPC_GEP_004_002
> IMPC_GEP_005_002
> IMPC_GEP_010_001
> IMPC_GEP_011_002
> IMPC_GEP_013_001
> IMPC_GEP_015_001
> IMPC_GEP_016_001
> IMPC_GEP_017_001
> IMPC_GEP_018_002
> IMPC_GEP_022_001
> IMPC_GEP_024_001
> IMPC_GEP_026_001
> IMPC_GEP_029_002
> IMPC_GEP_030_002
> IMPC_GEP_033_001
> IMPC_GEP_034_001
> IMPC_GEP_035_001
> IMPC_GEP_036_001
> IMPC_GEP_038_001
> IMPC_GEP_039_002
> IMPC_GEP_042_001
> IMPC_GEP_047_002
> IMPC_GEP_048_002
> IMPC_GEP_049_002
> IMPC_GEP_052_001
> IMPC_GEP_059_002
> IMPC_GEP_060_002
> IMPC_GEP_061_002
> IMPC_GEP_075_001
> IMPC_GEP_076_001
> IMPC_GEP_078_001
> IMPC_GEP_079_001
> IMPC_GEP_080_001
> IMPC_GEP_081_001
> IMPC_GEP_082_001
> IMPC_GEP_083_001
> IMPC_GEP_084_001
> IMPC_GEP_086_001
> IMPC_GEP_087_001
> IMPC_GPL_001_001
> IMPC_GPL_002_001
> IMPC_GPL_003_001
> IMPC_GPL_004_001
> IMPC_GPL_005_001
> IMPC_GPM_001_001
> IMPC_GPM_002_001
> IMPC_GPM_003_001
> IMPC_GPM_004_001
> IMPC_GPM_005_001
> IMPC_GPM_018_001
> IMPC_GPO_001_001
> IMPC_GPO_002_001
> IMPC_GPO_003_001
> IMPC_GPO_004_001
> IMPC_GPO_005_001
> IMPC_GPO_018_001
> IMPC_GPP_001_001
> IMPC_GPP_002_001
> IMPC_GPP_003_001
> IMPC_GPP_004_001
> IMPC_GPP_005_001
> IMPC_GPP_018_001
> ```
